# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.create(brand: 'Adidas', title: 'Yeezy Boost 700 Wave Runner', description: "This inaugural colorway of Kanye West’s Yeezy Wave Runner 700 launched in November 2017, following a public debut earlier in the year as part of the Yeezy Season 5 runway show.", price: 419.00, picture: "https://image.goat.com/crop/375/attachments/product_template_additional_pictures/images/014/507/858/original/195483_01.jpg.jpeg?1536271278", rdate: ("01-11-2017"))
Product.create(brand: 'Adidas', title: 'Yeezy Boost 350 V2 Synth Non-Reflective', description: "Through the Yeezy Boost 350 V2 'Synth Non-Reflective,' Kanye West continues the 350 V2's legacy, which began in 2016. This model was offered as a regional-exclusive release, made available to customers only in Africa, Asia and Australia. ", price: 330.00, picture: "https://image.goat.com/crop/375/attachments/product_template_pictures/images/022/928/042/original/synth.png", rdate: ("21-06-2019"))
Product.create(brand: 'Adidas', title: 'Pharrell x N.E.R.D. x NMD Human Race 20th Anniversary', description: "Crafted in partnership with the prolific musician and designer, this exclusive colorway of the Pharrell x N.E.R.D. x adidas NMD celebrates the 20th anniversary of N.E.R.D.’s debut album, ‘In Search Of …’ Wraparound rope laces secure an ivory Primeknit upper with tonal embroidered lettering atop the vamp: ‘N.E.R.D.’ spelled out on the right shoe, and Chinese characters that translate to ‘inner peace’ on the left.", price: 225.00, picture: "https://image.goat.com/crop/375/attachments/product_template_additional_pictures/images/058/444/360/original/797247_01.jpg.jpeg?1628256540", rdate: ("07-08-2021"))
Product.create(brand: 'Nike', title: 'Undefeated x Air Force 1 Low 5 On It', description: "Taken from the second installment of the LA retailer’s ‘Dunk vs. AF-1’ series, the Undefeated x Nike Air Force 1 Low ‘5 On It’ takes inspiration from sneaker culture during the late ‘90s and early 2000s, a period when exotic materials reigned supreme.", price: 223.00, picture: "https://image.goat.com/crop/375/attachments/product_template_additional_pictures/images/058/631/124/original/802662_01.jpg.jpeg?1628607807", rdate: ("07-08-2021"))
Product.create(brand: 'Nike', title: 'AMBUSH x Dunk High Flash Lime', description: "The AMBUSH x Nike Dunk High ‘Flash Lime’ brings Yoon Ahn’s distinct design vision to a fourth collaborative colorway of the retro hoops shoe. Inspired by Tokyo’s bright lights, the sneaker is entirely dipped in a fluorescent green hue, save for the co-branded tongue tag and a black TPU Swoosh that sweeps past the heel — a unique detail that recalls the look of motorcycle exhaust pipes.", price: 210.00, picture: "https://image.goat.com/crop/375/attachments/product_template_additional_pictures/images/058/281/140/original/796818_01.jpg.jpeg?1627996423", rdate: ("31-07-2021"))
Product.create(brand: 'Nike', title: 'Sean Wotherspoon x Air Max 1/97 Sean Wotherspoon', description: "Released for Air Max Day in 2018, this Sean Wotherspoon designed hybrid won the ‘Vote Forward’ campaign. This new creation combines the upper of an Air Max 97 with an Air Max 1 sole.", price: 1022.00, picture: "https://image.goat.com/crop/375/attachments/product_template_additional_pictures/images/011/255/124/original/329483_01.jpg.jpeg?1523485320", rdate: ("27-03-2018"))
